 # Exploratory Data Analysis

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv'
df = pd.read_csv(data_url)

In [3]:
# Set pandas option to display all columns
pd.set_option('display.max_rows', None)

In [4]:
# Display first few row of dataframe
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

# Step 3: Handling Missing Data
### Identify and manage missing values in critical columns such as Employment, JobSat, and RemoteWork. Implement a strategy to fill or drop these values, depending on the significance of the missing data.

In [5]:
# Handle missing value
print(df.shape)

(65437, 114)

In [6]:
missing_counts = df.isnull().sum()
print(missing_counts[missing_counts>0].sort_values(ascending=False))

AINextMuch less integrated        64289
AINextLess integrated             63082
AINextNo change                   52939
AINextMuch more integrated        51999
EmbeddedAdmired                   48704
EmbeddedWantToWorkWith            47837
EmbeddedHaveWorkedWith            43223
ConvertedCompYearly               42002
AIToolNot interested in Using     41023
AINextMore integrated             41009
Knowledge_9                       37802
Frequency_3                       37727
Knowledge_8                       37679
ProfessionalTech                  37673
Knowledge_7                       37659
Knowledge_6                       37573
Knowledge_5                       37557
Knowledge_2                       37416
Knowledge_4                       37407
Knowledge_3                       37342
Frustration                       37186
Frequency_2                       37073
Frequency_1                       37068
ProfessionalCloud                 36946
Knowledge_1                       36773
ProfessionalQuestion              36630
TimeAnswering                     36593
Industry                          36579
TimeSearching                     36526
JobSat                            36311
JobSatPoints_1                    36113
JobSatPoints_4                    36044
JobSatPoints_5                    36026
JobSatPoints_11                   35992
JobSatPoints_7                    35989
JobSatPoints_10                   35987
JobSatPoints_6                    35987
JobSatPoints_9                    35981
JobSatPoints_8                    35981
MiscTechAdmired                   35841
WorkExp                           35779
ICorPM                            35636
AIToolInterested in Using         34746
PlatformAdmired                   34060
MiscTechWantToWorkWith            32473
CompTotal                         31697
PlatformWantToWorkWith            30905
WebframeAdmired                   30494
AIToolCurrently Using             30365
AISearchDevAdmired                29894
AISearchDevWantToWorkWith         28736
AIBen                             28543
AIComplex                         28416
OfficeStackAsyncAdmired           28233
AIAcc                             28135
AIChallenges                      27906
WebframeWantToWorkWith            26902
DatabaseAdmired                   26880
OfficeStackAsyncWantToWorkWith    26471
MiscTechHaveWorkedWith            25994
TechDoc                           24540
AIEthics                          23889
PlatformHaveWorkedWith            23071
DatabaseWantToWorkWith            22879
BuildvsBuy                        22079
TechEndorse                       21769
ToolsTechAdmired                  21440
AISearchDevHaveWorkedWith         20984
TBranch                           20960
AIThreat                          20748
OfficeStackSyncAdmired            20725
WebframeHaveWorkedWith            20276
BuyNewTool                        20256
SOPartFreq                        20200
AISent                            19564
ToolsTechWantToWorkWith           19353
Currency                          18753
OfficeStackSyncWantToWorkWith     18726
PurchaseInfluence                 18031
OrgSize                           17957
OfficeStackAsyncHaveWorkedWith    17344
LearnCodeOnline                   16200
DatabaseHaveWorkedWith            15183
NEWCollabToolsAdmired             14726
LanguageAdmired                   14565
YearsCodePro                      13827
NEWCollabToolsWantToWorkWith      13350
ToolsTechHaveWorkedWith           12955
OpSysProfessional use             12464
CodingActivities                  10971
RemoteWork                        10631
OfficeStackSyncHaveWorkedWith      9892
LanguageWantToWorkWith             9685
SurveyLength                       9255
SurveyEase                         9199
NEWCollabToolsHaveWorkedWith       7845
OpSysPersonal use                  7263
Country                            6507
SOHow                              6475
SOComm                             6274
DevType                            5992
SOVisitFreq                        5901
SOAccount                          5877
LanguageHaveWorkedWith             5692
YearsCode                          5568
NEWSOSites                         5151
LearnCode                          4949
EdLevel                            4653
AISelect                           4530
dtype: int64

In [7]:
# Calculate the threshold for 50% missing data
threshold = df.shape[0] * 0.20  # No need for int casting, it's not necessary
print(threshold)

# Drop columns with more than 50% missing values
df = df.dropna(thresh=threshold, axis=1)

13087.400000000001

In [8]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [9]:
print(df.shape)

(65437, 111)

In [10]:
# Again check the missing value
missing_counts = df.isnull().sum()
print(missing_counts[missing_counts>0].sort_values(ascending=False))

AINextMuch more integrated        51999
EmbeddedAdmired                   48704
EmbeddedWantToWorkWith            47837
EmbeddedHaveWorkedWith            43223
ConvertedCompYearly               42002
AIToolNot interested in Using     41023
AINextMore integrated             41009
Knowledge_9                       37802
Frequency_3                       37727
Knowledge_8                       37679
ProfessionalTech                  37673
Knowledge_7                       37659
Knowledge_6                       37573
Knowledge_5                       37557
Knowledge_2                       37416
Knowledge_4                       37407
Knowledge_3                       37342
Frustration                       37186
Frequency_2                       37073
Frequency_1                       37068
ProfessionalCloud                 36946
Knowledge_1                       36773
ProfessionalQuestion              36630
TimeAnswering                     36593
Industry                          36579
TimeSearching                     36526
JobSat                            36311
JobSatPoints_1                    36113
JobSatPoints_4                    36044
JobSatPoints_5                    36026
JobSatPoints_11                   35992
JobSatPoints_7                    35989
JobSatPoints_10                   35987
JobSatPoints_6                    35987
JobSatPoints_9                    35981
JobSatPoints_8                    35981
MiscTechAdmired                   35841
WorkExp                           35779
ICorPM                            35636
AIToolInterested in Using         34746
PlatformAdmired                   34060
MiscTechWantToWorkWith            32473
CompTotal                         31697
PlatformWantToWorkWith            30905
WebframeAdmired                   30494
AIToolCurrently Using             30365
AISearchDevAdmired                29894
AISearchDevWantToWorkWith         28736
AIBen                             28543
AIComplex                         28416
OfficeStackAsyncAdmired           28233
AIAcc                             28135
AIChallenges                      27906
WebframeWantToWorkWith            26902
DatabaseAdmired                   26880
OfficeStackAsyncWantToWorkWith    26471
MiscTechHaveWorkedWith            25994
TechDoc                           24540
AIEthics                          23889
PlatformHaveWorkedWith            23071
DatabaseWantToWorkWith            22879
BuildvsBuy                        22079
TechEndorse                       21769
ToolsTechAdmired                  21440
AISearchDevHaveWorkedWith         20984
TBranch                           20960
AIThreat                          20748
OfficeStackSyncAdmired            20725
WebframeHaveWorkedWith            20276
BuyNewTool                        20256
SOPartFreq                        20200
AISent                            19564
ToolsTechWantToWorkWith           19353
Currency                          18753
OfficeStackSyncWantToWorkWith     18726
PurchaseInfluence                 18031
OrgSize                           17957
OfficeStackAsyncHaveWorkedWith    17344
LearnCodeOnline                   16200
DatabaseHaveWorkedWith            15183
NEWCollabToolsAdmired             14726
LanguageAdmired                   14565
YearsCodePro                      13827
NEWCollabToolsWantToWorkWith      13350
ToolsTechHaveWorkedWith           12955
OpSysProfessional use             12464
CodingActivities                  10971
RemoteWork                        10631
OfficeStackSyncHaveWorkedWith      9892
LanguageWantToWorkWith             9685
SurveyLength                       9255
SurveyEase                         9199
NEWCollabToolsHaveWorkedWith       7845
OpSysPersonal use                  7263
Country                            6507
SOHow                              6475
SOComm                             6274
DevType                            5992
SOVisitFreq                        5901
SOAccount                          5877
LanguageHaveWorkedWith             5692
YearsCode                          5568
NEWSOSites                         5151
LearnCode                          4949
EdLevel                            4653
AISelect                           4530
dtype: int64

In [19]:
# Fill Categorical data with mode
for col in df.select_dtypes(include='object'):
    mode_value = df[col].mode()[0]
    # df[col].fillna(mode_value, inplace=True) # Old way
    df[col] = df[col].fillna(mode_value)  # New way

In [24]:
df[df.isnull().any(axis=1)].head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Easy,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [26]:
# Fill Numerical data with ??
for col in df.select_dtypes(include='float'):
    mean_value = df[col].mean()
    df[col] = df[col].fillna(mean_value)

In [37]:
null_columns = df.columns[df.isnull().any()].tolist()
print("Columns with missing values:")
print(null_columns)
for col in null_columns:
    print(f"Column: {col}, Missing: {df[col].isnull().sum()}, Dtype: {df[col].dtype}")

Columns with missing values:
[]

In [38]:
missing_counts = df.isnull().sum()
print(missing_counts[missing_counts>0].sort_values(ascending=False))

Series([], dtype: int64)

In [ ]:
missing_counts = df.isnull().sum()
only_missing = missing_counts[missing_counts > 0]
print("Columns with missing values:")
print(only_missing)

Columns with missing values:
Series([], dtype: int64)